permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: ""
email: sincerebravefight@gmail.com
description: Lambda
github_username:  WakelessDragon
swiftype_searchId: ncwR9a8S9CTx2q9SgsJm
gitment:
    owner: WakelessDragon
    repo: blog
    client_id: a6fb73b3e790e234bab8
    client_secret: cc10aaff53a03d05ab2ee002dbf401dd7627c7a3



url: "http://wakelessdragon.github.io/blog"
imgrepo: "http://wakelessdragon.github.io/blog/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

