baseurl: ""
permalink: /:year-:month-:day/:title
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
desc: "征途：星辰大海！"
author: "RainyNight"
