permalink: /:year-:month-:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

code_theme: "monokai_sublime"
paginate: 10
paginate_path: ":num"

baseurl: ""

title: "RainyNight"
email: "dubuyuye@yeah.net"
description: "Born to Die"
github_username:  "dubuyuye"

url: "http://blog.rainynight.top"
imgrepo: "http://blog.rainynight.top/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

