baseurl: ""
feedRoot: "http://blog.rainynight.top/"
permalink: /:year-:month-:day/:title
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
desc: "我们的征途是星辰大海！"
author: "RainyNight"
rssLink: "/feed"
github: "https://github.com/dubuyuye/blog"
