permalink: /:year-:month-:day/:title/
markdown: kramdown
baseurl: ""
siteurl: "http://blog.rainynight.top"

title: "RainyNight"
email: "dubuyuye@yeah.net"
description: "Born to Die"
github_username:  "dubuyuye"

imgrepo: "http://blog.rainynight.top/static/img"
#imgrepo: "http://127.0.0.1:4000/static/img"